name: Daily site rebuild
on:
  schedule:
    - cron: '0 3 * * *' # Every night at 03:00
jobs:
  build:
    name: Request rebuild via hook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6343d562ac2fc7553508e456
